### ISSUE TITLE
Crossing Dimensions Poster

### ISSUE THREAD

**Issue by Zorth** [TarragonVZW/tarragonvzw.github.io#19]
- Must be reusable
- portal idea?

**Comment by Zorth** [comment]
![Image](https://github.com/TarragonVZW/tarragonvzw.github.io/assets/16945970/e9965025-d1a1-4190-8c6e-b51422240275)

First Idea (missing character coming out of portal)

**Comment by Zorth** [comment]
![Image](https://github.com/TarragonVZW/tarragonvzw.github.io/assets/16945970/ffa1cc89-4a9d-4e9e-af9f-eb2b36f1e897)
![Image](https://github.com/TarragonVZW/tarragonvzw.github.io/assets/16945970/80a126cf-439a-4628-86d8-350137817854)
![Image](https://github.com/TarragonVZW/tarragonvzw.github.io/assets/16945970/bce71035-6b05-48ab-aa6b-81811235bf67)
![Image](https://github.com/TarragonVZW/tarragonvzw.github.io/assets/16945970/f2c1a14d-99d9-424d-b9c3-c921c01de94a)
![Image](https://github.com/TarragonVZW/tarragonvzw.github.io/assets/16945970/68f17585-f35f-4aa6-baec-fe1a09859146)
![Image](https://github.com/TarragonVZW/tarragonvzw.github.io/assets/16945970/a9a090d6-0e3c-4589-948e-c732ea93a59d)

**Comment by Zorth** [comment]
- transformation idea
- "Medieval" & "Pokemon" go to vertical design, iteratations
- Color & contrast is important
- Keep different sizes in mind

**Comment by SilverLionfang** [comment]
Deadline was today, but no work has been posted. New deadline: Wednesday the 27th of December.

**Comment by Zorth** [comment]
I could not find most information needed. All text is placeholder for @TarragonVZW/pr 

![Image](https://github.com/TarragonVZW/tarragonvzw.github.io/assets/16945970/52d87f94-2d04-4e68-9f51-71204a5f796c)

**Comment by PhaedraLambrecht** [comment]
Date => correct
Time => niet correct (begint vanaf 18)
