### ISSUE TITLE
Crossing Dimenions Minigame 01

### ISSUE THREAD

**Issue by SilverLionfang** [TarragonVZW/tarragonvzw.github.io#30]
All dragons make 2 minigames by 19/11/2023.

**Comment by Bert-Moors** [comment]
spoon with ball slalom
mini quiz 5 questions
beer pong without beer just throw ball in cups 

for a minigame against a group maybe touwtje trek?

**Comment by SilverLionfang** [comment]
Build human pyramid
Transfer a card mouth to mout

**Comment by Zorth** [comment]
## Duel style
- Throw dice into a box (highest number on dice wins)
- Nerf Duel
- Pictionary
- Charades
- Cornhole
## Challenge style
- Easy chess puzzle
- Time trial slide puzzle

**Comment by SamVangeluwe** [comment]
Some extra minigames:

Stacking cups ( the cup song style)

Chubby bunny ( this requires food )

Oneline drawings ( most recognisable, best,...)

"Tfk is that?"( Give them a foreign word and see who can guess what it means

15min escape room

**Comment by GrimmSlayingDolt** [comment]
- Copy cat: Choose someone to be the ‘Copycat Catcher.’ Explain that it’ll be their job to work out who’s starting the actions that everyone else is copying.
- interceptor:  work together to pass the ball to everyone in your team without the other team intercepting it.
- cornhole: take turns throwing fabric bean bags at a raised, angled board with a hole in it

**Comment by Cistem35** [comment]
Moving 2 (or more) balls from point A to point B without using your arms and legs (can be something else than balls if needed)

Depending on group size people would need to have as a group 5 legs and and 7 arms to touch to ground (still requires some testing to see what is possible and what not)

**Comment by Bork114** [comment]
- Small challenges where they can only use their feet ( Opening a bag, ordering something from small to big)
- Garticphone
- Appel bobbing ( take an apple from a basin filled with water.

**Comment by PhaedraLambrecht** [comment]
charades/ pictionary
--> can also be a draw it game


Mystery chalanges:
--> tic-tac-toe (between 2 groups potentially or with a dragon)
--> memory game
--> cup stack race
--> target shooting (if we have nerf guns)
--> riddles and enigmas (solving)
