### ISSUE TITLE
Workshop Night Form

### ISSUE THREAD

**Issue by Zorth** [TarragonVZW/tarragonvzw.github.io#35]
- What workshops will you be joining? (mini painting, drawing, crocheting, writing)
    - Mini painting sign up, you get to keep your mini (if you want), 10 euro, 8 euro for kobolds
    - crocheting sign up, you get to keep your work, 10 euro, 8 euro for kobolds
    - Character drawing, bring your own materials (drawing/painting, paper, strong backing to draw on), free
    - Writing, bring something to write on and with, free
  - Transfer 10 euros (8 for kobolds) to
```
Tarragon
BE18 7330 7200 6665
BIC KREDBEBB
Message:
Workshop Firstname Lastname
```

**Comment by PhaedraLambrecht** [comment]
Form has been made with the use of sections

**Comment by PhaedraLambrecht** [comment]
The answers of the form are put into an excel document so everyone has access to it.
there is a checkbox field that if the box is checked the person has paid, makes it easier to check later on.
