### ISSUE TITLE
Crossing Dimension Minigame 02

### ISSUE THREAD

**Issue by SilverLionfang** [TarragonVZW/tarragonvzw.github.io#37]

**Comment by GrimmSlayingDolt** [comment]
**Mini games:**

1. Helium stick: 
- Materials: a long thin stick or tent pole
- Split the team into two lines facing each other, have them raise their arms and point both their index fingers out forward. Place the stick across their fingers. The stick should be at the chest level height of the tallest participant to start. Once the stick is laying across participants fingers, tell them that their challenge is to lower this stick to the ground but keep it level. Everyone's finger must remain in contact with the stick at all times during the challenge. If it slips, they have to start from the beginning. Pinching or grabbing the stick with other fingers is considered cheating. 
- Reference: https://www.youtube.com/watch?v=rL1JCxEHogg

2. Birthday lineup: 
- Materials: none
- The team has to form a line in the order of their birthdays without talking to each other. You can add a time limit to add pressure and excitement to the game.
 
3. Perfect square:
- Materials: a rope, 6 blindfolds (towels)
- Stand in a tight circle with their group, have them blindfold themselves and give one person a rope. The team now has to pass the rope around so everyone holds a piece of it and then form a perfect square. Once the team is sure their square is perfect, they can lay the rope down on the floor, take off their blindfolds and see how well they did. 

4. Keep it up:
- Materials: a balloon, beach ball, or volleyball
- Stand in a circle and keep the balloon or ball in the air for a set goal of X amount of seconds. To make it a real challenge, no one can touch the ball twice in a row. If you’re struggling to keep the ball up for the decided time, try to come up with a strategy to improve it.

5. Electric fence:
- Materials: two chairs and a rope or pole
- The team must cross over the fence without touching it. To get from one side to the other, members must go over, not under, one at a time. They also must be touching another member of the group with at least one hand at all times. Participants should not make any contact with the electric fence at anytime. If they violate one of the two rules, they must start the exercise all over again. 
- Reference: https://www.youtube.com/watch?v=t0FaWhRaVbY&t=384s

6. Reverse Charades:
- Materials: paper with a list of charade words, a phone/screen where time visibly goes by.
- The team must work together to act out a word or phrase while only one person needs to guess. They have 60 seconds to play out and guess as many words as possible.
- Reference https://www.youtube.com/watch?v=sfXg6cR3BMw&t=282s

**Team vs team challenges**

1. Clothes chain:
- Materials: none
- Make the longest chain of clothes within 5 minutes from the clothes which the team members are wearing.

2. Scavenger run:
- Materials: various items of choice (ideally have some items be similar yet have a key difference)
- Have two teams sit in a row next to each other. An object gets called out (or you tell a story and pause the moment you say the name of an object). The players first in the line must then get up and be be the first to bring back the correct object. That team gets a point, the one with most points wins. All of the players move a place forward in the line and the player who has just taken part goes to the back. 

3. Four legged spider:
- Materials: painters tame to mark start and finish line
- Two teams have to cross a certain distance together, while only allowed to use x feet without falling. Every member must touch another at all times. If you break a rule you must start over, the first to cross the finish line wins. (6 people = 5 feet)

4. Falling cards:
- Materials: playing cards, a bottle or cup to place the cards on
- A pile of playing cards is put on the top of a bottle. The first team to be able to blow all cards off first wins.

5. Blind guardian:
- Materials: 6 blindfolds, 3 chairs and 3 objects to place under it
- Place 3 chairs and put an object under each. The blindfolded team must guard the 3 stools to make sure the others cannot take the objects back to their base. Anyone who is tagged by a blindfolded player must place the object back and start again from their base. Toss a coin, heads means blind team. The seeing teams wins if all objects are stolen in x amount of time, the blind team wins if any item remains within that time.

**Comment by SilverLionfang** [comment]
### Mini game 1: Count Up

- Materials: 6 Blindfold (Towels)
- The team gets 30 seconds to count to twenty. People cannot say more than one number at the time. If they speak at the same time, they have to start over. Once they answered after someone, they cannot answer after that team member anymore. Once they get to 20, they succeed. They have 5 attempts to do so.

### Mini game 2: Cup Stack -> Ball Toss
- Materials: (6) Small balls, 20 cups
- The team has to set up 20 cups in any way they want and stand behind the line 10 meters away to knock it down. They each have a ball to throw.

### Mini game 3: Number Generation
- Materials: Paper with a single digit number on it.
- Each team member will be given a number. The Dragon will call a number and they have to arrange to make that number. They have to do so 5 times within a time limit of 30 seconds. [Give one the number zero and you'll be able to call out a number below 100 000]

### Mini game 4: The Secret Dragon Shake
- Materials: /
- All team members stand in a line facing away from the Dragon. The Dragon taps the first in line and teaches them a secret handshake. That member then has to perform the handshake next in line until they get to the last in line.

**Comment by BrenainnVanhaverbeke** [comment]
# Minefield
There's a premade grid where there's only one safe path to go from one end to the other. 
Team members take turns to attempt the crossing, as soon as an attempt is being made there may be no communication between the team and the runner. 
If the runner trips a mine, they return to the start and team needs to discuss how to continue and gradually figure out the safe path over several attempts.
Everyone gets 1 turn, resets when everyone's made an attempt?
## Materials:
- Anything to delineate a grid
- Premade route
# Know Thy Dragons
We give a group our pictures and a bunch of statements/facts. 
The team has to attach the statements to our pictures and succeed if they have at least x correct links.
## Materials
- Our pictures
- Paper notes with the statements/facts.
