### ISSUE TITLE
ESN Board Game Night Format

### ISSUE THREAD

**Issue by Zorth** [TarragonVZW/tarragonvzw.github.io#8]
28-11-2023

**Comment by Bert-Moors** [comment]
3 large tables for the longer games
3-4 tables for the smaller games 

smaller games will be mostly 4 player so maybe can fit 2 groups at the bar table?
### Longer games
captain sonar, cash and guns (teamplay), pandemic, monster hunter, betrayal(maybe), 
### shorter Games
codenames, dogfight, revolver noir, sprawlopolis (and other opolis games), battlecrest, royale 

longer games still need some work bc shouldn't be too long and would be nice if they can fit a fair number of people

**Comment by Zorth** [comment]
@SilverLionfang reserves tabels at crafty's

**Comment by Zorth** [comment]
Who's attending? @TarragonVZW/dragons 
Who does which games?

**Comment by Bork114** [comment]
Attending: Cis, Stef, Mattis, Bert, Brennain
Games:
**Long**
Monster Hunter -> Brennain
Captain Sonar -> Bert
Cash and Guns -> Mattis

**Short** -> Stef, Cis
Codenames 
Dogfight
Revolver Noir
Sprawlopolis 
Battlecrest
Royale
